/* section3chars, shelf, row, bookId */
INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 1, 1);
INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 1, 2);
INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 1, 3);
INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 1, 4);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 1, 5);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 1, 6);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 1, 7);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 2, 8);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 2, 9);

INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 1, 10);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 1, 11);

INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 1, 12);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 1, 13);

/*6*/
INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 1, 14);
INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 1, 15);
INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 1, 16);
INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 1, 17);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 2, 18);

INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 2, 19);
INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 2, 20);

INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 3, 21);
INSERT INTO BOOKSPOSITION VALUES ('FNT', 1, 3, 22);

INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 1, 23);

/*11*/
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 2, 24);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 2, 25);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 2, 26);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 2, 27);

INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 2, 28);
INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 2, 29);

INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 2, 30);

INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 3, 31);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 32);

/*16*/
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 3, 33);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 3, 34);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 3, 35);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 3, 36);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 3, 37);

INSERT INTO BOOKSPOSITION VALUES ('ROM', 1, 2, 38);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 39);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 40);


INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 4, 41);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 4, 42);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 4, 43);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 4, 44);

/*21*/
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 2, 45);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 2, 46);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 2, 47);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 2, 1, 48);


INSERT INTO BOOKSPOSITION VALUES ('CLS', 2, 1, 49);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 2, 1, 50);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 2, 2, 51);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 2, 2, 52);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 2, 2, 53);

INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 54);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 55);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 56);
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 57);

/*26*/
INSERT INTO BOOKSPOSITION VALUES ('CLS', 1, 3, 58);

INSERT INTO BOOKSPOSITION VALUES ('OTH', 1, 1, 59);
INSERT INTO BOOKSPOSITION VALUES ('OTH', 1, 1, 60);

INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 3, 61);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 3, 62);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 3, 63);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 3, 64);

INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 4, 65);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 4, 66);
INSERT INTO BOOKSPOSITION VALUES ('ACT', 1, 4, 67);

INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 4, 68);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 4, 69);
INSERT INTO BOOKSPOSITION VALUES ('HST', 1, 4, 70);
COMMIT;