INSERT INTO BOOKSECTIONS VALUES ('HST', 1, 1);
INSERT INTO BOOKSECTIONS VALUES ('CLS', 1, 1);
INSERT INTO BOOKSECTIONS VALUES ('OTH', 1, 1);
INSERT INTO BOOKSECTIONS VALUES ('ACT', 1, 1);
INSERT INTO BOOKSECTIONS VALUES ('FNT', 1, 1);
COMMIT;