INSERT INTO BOOKSECTIONS VALUES ('HST');
INSERT INTO BOOKSECTIONS VALUES ('CLS');
INSERT INTO BOOKSECTIONS VALUES ('OTH');
INSERT INTO BOOKSECTIONS VALUES ('ACT');
INSERT INTO BOOKSECTIONS VALUES ('FNT');
COMMIT;