INSERT INTO CATALOGFULLYEARPRICES VALUES (1, 'PRESCHOOLER', 0);
INSERT INTO CATALOGFULLYEARPRICES VALUES (1, 'PUPILS', 200);
INSERT INTO CATALOGFULLYEARPRICES VALUES (1, 'STUDENT', 250);
INSERT INTO CATALOGFULLYEARPRICES VALUES (1, 'REGULAR', 500);
INSERT INTO CATALOGFULLYEARPRICES VALUES (1, 'RETIRED', 0);
INSERT INTO CATALOGFULLYEARPRICES VALUES (1, 'PRIVILEGED', 0);

UPDATE CATALOGFULLYEARPRICES SET TYPE = 'PUPIL' WHERE TYPE = 'PUPILS';
COMMIT;