INSERT INTO CATALOGHALFAYEARPRICES VALUES (1, 'PRESCHOOLER', 0);
INSERT INTO CATALOGHALFAYEARPRICES VALUES (1, 'PUPILS', 125);
INSERT INTO CATALOGHALFAYEARPRICES VALUES (1, 'STUDENT', 150);
INSERT INTO CATALOGHALFAYEARPRICES VALUES (1, 'REGULAR', 300);
INSERT INTO CATALOGHALFAYEARPRICES VALUES (1, 'RETIRED', 0);
INSERT INTO CATALOGHALFAYEARPRICES VALUES (1, 'PRIVILEGED', 0);

UPDATE CATALOGHALFAYEARPRICES SET TYPE = 'PUPIL' WHERE TYPE = 'PUPILS';
COMMIT;