INSERT INTO MAXISSUEDBOOKS VALUES ('PRESCHOOLER', 3);
INSERT INTO MAXISSUEDBOOKS VALUES ('PUPILS', 3);
INSERT INTO MAXISSUEDBOOKS VALUES ('STUDENTS', 3);
INSERT INTO MAXISSUEDBOOKS VALUES ('REGULAR', 5);
INSERT INTO MAXISSUEDBOOKS VALUES ('RETIRED', 3);
INSERT INTO MAXISSUEDBOOKS VALUES ('PRIVILEGED', 10);

UPDATE MAXISSUEDBOOKS SET TYPE = 'PUPIL' WHERE TYPE = 'PUPILS';
UPDATE MAXISSUEDBOOKS SET TYPE = 'STUDENT' WHERE TYPE = 'STUDENTS';
COMMIT;