INSERT INTO MAXISSUEDAYS VALUES ('PRESCHOOLER', 20);
INSERT INTO MAXISSUEDAYS VALUES ('PUPILS', 15);
INSERT INTO MAXISSUEDAYS VALUES ('STUDENTS', 15);
INSERT INTO MAXISSUEDAYS VALUES ('REGULAR', 15);
INSERT INTO MAXISSUEDAYS VALUES ('RETIRED', 21);
INSERT INTO MAXISSUEDAYS VALUES ('PRIVILEGED', 30);
COMMIT;